// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxi41yKyoS0Apwqn4NNGH51vL5CU_F4AU',
    appId: '1:1082023733271:web:c8978a389026a6ce17d452',
    messagingSenderId: '1082023733271',
    projectId: 'neurohelp-95e92',
    authDomain: 'neurohelp-95e92.firebaseapp.com',
    storageBucket: 'neurohelp-95e92.firebasestorage.app',
    measurementId: 'G-47QW3HMJP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA29ske8F-9mEwHRr-tAZniy3gD7iTW8Bw',
    appId: '1:1082023733271:android:0578b6b7f47df2dd17d452',
    messagingSenderId: '1082023733271',
    projectId: 'neurohelp-95e92',
    storageBucket: 'neurohelp-95e92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-NL9X3CtHQ3dPlXX7rt1FDzJWqbh1kEU',
    appId: '1:1082023733271:ios:fb23986f768b06d017d452',
    messagingSenderId: '1082023733271',
    projectId: 'neurohelp-95e92',
    storageBucket: 'neurohelp-95e92.firebasestorage.app',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-NL9X3CtHQ3dPlXX7rt1FDzJWqbh1kEU',
    appId: '1:1082023733271:ios:fb23986f768b06d017d452',
    messagingSenderId: '1082023733271',
    projectId: 'neurohelp-95e92',
    storageBucket: 'neurohelp-95e92.firebasestorage.app',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxi41yKyoS0Apwqn4NNGH51vL5CU_F4AU',
    appId: '1:1082023733271:web:8d6927c9fc11ef2f17d452',
    messagingSenderId: '1082023733271',
    projectId: 'neurohelp-95e92',
    authDomain: 'neurohelp-95e92.firebaseapp.com',
    storageBucket: 'neurohelp-95e92.firebasestorage.app',
    measurementId: 'G-8JT31B8BSP',
  );
}
